<?php

// Activation des différents supports
add_theme_support('title-tag');
add_theme_support('post-thumbnails');

// Remove p and br autogenerated by CF7
add_filter('wpcf7_autop_or_not', '__return_false');

// Définition des tailles d'images perso
add_image_size('img-presentation', 310, 440, true);
add_image_size('card-illustration', 320, 480, true);
add_image_size('hero', 1020, 680, true);
add_image_size('recipe-thumbnail', 485, 600, true);
add_image_size('recipe-illustration', 485, 485, true);

// Création des emplacements menu
register_nav_menus(array(
    'main' => 'Menu principal',
    'footer' => 'Menu de pied de page',
    'social' => 'Menu des réseaux sociaux'
));

// Modifier le nombre de mots des extraits
function wpm_post_excerpt($length)
{
    return 20;
}
add_filter('excerpt_length', 'wpm_post_excerpt');

// Modifier la boucle WP
function dwwm_override_query($wp_query)
{
    global $wp_the_query;
    if ($wp_query->is_main_query() and is_home()) {
        $nb = get_field('archive_posts_nb', 'option');
        if ($nb) $wp_query->set('posts_per_page', $nb);
    }
    if ($wp_query->is_main_query() and is_post_type_archive('recette')) {
        $nb = get_field('archive_recipes_nb', 'option');
        if ($nb) $wp_query->set('posts_per_page', $nb);
        else $wp_query->set('posts_per_page', 12);
    }
    if ($wp_query === $wp_the_query && $wp_query->is_search()) {
        $wp_query->set('posts_per_page', 12);
    }
}
add_action('pre_get_posts', 'dwwm_override_query');

// Chargement des feuilles de styles et scripts JS
function dwwm_stylesheets_and_scripts()
{
    wp_enqueue_style('reset', get_template_directory_uri() . '/css/reset.css', array(), '1.0');
    wp_enqueue_style('style', get_template_directory_uri() . '/css/style.css', array('reset'), '1.0');
}
add_action('wp_enqueue_scripts', 'dwwm_stylesheets_and_scripts');

/* Création des CPT */
function dwwm_register_post_types()
{
    /* CPT Recettes */
    $labels = array(
        'name' => 'Recettes',
        'all_items' => 'Toutes les recettes',
        'singular_name' => 'Recette',
        'add_new_item' => 'Ajouter une recette',
        'edit_item' => 'Modifier la recette',
        'menu_name' => 'Mes recettes'
    );
    $args = array(
        'labels' => $labels,
        'public' => true,
        'has_archive' => true,
        'menu_icon' => 'dashicons-food',
        'menu_position' => 5,
        'supports' => array('title', 'thumbnail'),
        'taxonomies' => array('genre'),
    );
    register_post_type('recette', $args);

    /* Taxonomie Genre */
    $labels = array(
        'name' => 'Genre de recette'
    );
    $args = array(
        'labels' => $labels,
        'public' => true,
        'hierarchical' => false,
        'has_archive' => true,
    );
    register_taxonomy('genre', 'recette', $args);
}
add_action('init', 'dwwm_register_post_types');

/* Déclaration des pages d'options ACF du thème */
if (function_exists('acf_add_options_page')) {
    acf_add_options_page(array(
        'page_title'     => 'Paramétrage du thème',
        'menu_title'    => 'Paramétrage',
        'menu_slug'     => 'theme-general-settings',
        'capability'    => 'edit_others_posts',
        'redirect'        => true
    ));

    acf_add_options_sub_page(array(
        'page_title'     => 'Paramètres Généraux',
        'menu_title'    => 'Général',
        'parent_slug'    => 'theme-general-settings',
    ));

    acf_add_options_sub_page(array(
        'page_title'     => 'Erreur 404',
        'menu_title'    => 'Erreur 404',
        'parent_slug'    => 'theme-general-settings',
    ));
}

/**
 * Disable Editor
 *
 * @package      ClientName
 * @author       Bill Erickson
 * @since        1.0.0
 * @license      GPL-2.0+
 **/

/**
 * Templates and Page IDs without editor
 *
 */
function ea_disable_editor($id = false)
{

    $excluded_templates = array(
        'templates/modules.php',
        'templates/contact.php'
    );

    $excluded_ids = array(
        // get_option( 'page_on_front' )
    );

    if (empty($id))
        return false;

    $id = intval($id);
    $template = get_page_template_slug($id);

    return in_array($id, $excluded_ids) || in_array($template, $excluded_templates);
}

/**
 * Disable Gutenberg by template
 *
 */
function ea_disable_gutenberg($can_edit, $post_type)
{

    if (!(is_admin() && !empty($_GET['post'])))
        return $can_edit;

    if (ea_disable_editor($_GET['post']))
        $can_edit = false;

    return $can_edit;
}
add_filter('gutenberg_can_edit_post_type', 'ea_disable_gutenberg', 10, 2);
add_filter('use_block_editor_for_post_type', 'ea_disable_gutenberg', 10, 2);

/**
 * Disable Classic Editor by template
 *
 */
function ea_disable_classic_editor()
{

    $screen = get_current_screen();
    if ('page' !== $screen->id || !isset($_GET['post']))
        return;

    if (ea_disable_editor($_GET['post'])) {
        remove_post_type_support('page', 'editor');
    }
}
add_action('admin_head', 'ea_disable_classic_editor');
